version: '3.8'

services:
#  db:
#    image: postgres:16
#    container_name: sensors_db
#    environment:
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin
#      POSTGRES_DB: sensor_base
#    ports:
#      - "5432:5432"
#    volumes:
#      - db_data:/var/lib/postgresql/data
  api:
    build: .
    container_name: eyeident_server
    ports:
      - "8080:8080"
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: eyeiden_database
      DB_HOST: eyeident-db-leorius.db-msk0.amvera.tech
      DB_PORT: 5432

#volumes:
#  db_data:
